### ISSUE TITLE
['Кабінет' Tab, Main page] The password with 8 symbols instead of 9 symbols is accepted without any error messages after entering data into mandatory field

### ISSUE THREAD

**Issue by Viktoriia0106** [kamilka13me/marketplace_teamchallenge#129]
**Environment:**

Windows 10 22H2 19045.4046, 64-bit
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** always

**Build found:** 18.03.2024_14:30

**Steps to reproduce:**

1. The [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) site is opened
2. Click the ‘Кабінет’ icon in the header of the site
3. Enter a valid E-mail (e.g. peach@ukr.net)
4. Enter a password - any 8 symbols 
5. Pay attention to the result 

**Actual result:**
The password with 8 symbols instead of 9 symbols is accepted without any error messages after entering data into mandatory field

**Expected result:**
The password less than 9 symbols is not accepted and the error message is appeared, 'Увійти' button is not active 

 [User story MT-15](https://marketplacetc.atlassian.net/browse/MT-15)

![8 symbols instesd 9 accepted](https://github.com/kamilka13me/marketplace_teamchallenge/assets/109147739/d72c84fe-4dcc-455d-866c-a37b406d64ec)

**Comment by olehivanovw** [comment]
Fix @Viktoriia0106, Added this check to the password field in the login form.

Actual result:
The password less than 9 symbols is not accepted and the error message is appeared, 'Увійти' button is not active

![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/121825752/f3bf8945-9a95-4f56-acc4-ad3e17406b59)

Please make this issue is closed if the bug is fixed.
